# Generated by Django 4.2.23 on 2026-06-09 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('operation', 'На основе рабочих операций'), ('function', 'На основе трудовой функции'), ('day', 'На основе рабочего дня')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('formula_hint', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Стратегия расчёта',
                'verbose_name_plural': 'Стратегии расчёта',
            },
        ),
        migrations.CreateModel(
            name='NoiseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('strategy', models.CharField(choices=[('operation', 'На основе рабочих операций'), ('function', 'На основе трудовой функции'), ('day', 'На основе рабочего дня')], max_length=20, verbose_name='Стратегия расчёта')),
                ('num_points', models.IntegerField(verbose_name='Количество точек замеров')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замер шума',
                'verbose_name_plural': 'Замеры шума',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('short_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NoiseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lex_8h', models.FloatField(verbose_name='L_EX,8h, дБ')),
                ('std_deviation', models.FloatField(verbose_name='Стандартное отклонение')),
                ('max_noise', models.FloatField(verbose_name='Максимальное значение, дБ')),
                ('min_noise', models.FloatField(verbose_name='Минимальное значение, дБ')),
                ('norm_value', models.FloatField(default=80.0, verbose_name='ПДУ, дБ')),
                ('exceeds_norm', models.BooleanField(verbose_name='Превышение нормы')),
                ('recommendations', models.TextField(verbose_name='Рекомендации')),
                ('chart_path', models.CharField(blank=True, max_length=512)),
                ('pdf_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='noise.noisemeasurement')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField(verbose_name='Номер точки')),
                ('noise_db', models.FloatField(verbose_name='Уровень шума, дБ')),
                ('duration_min', models.FloatField(blank=True, null=True, verbose_name='Длительность, мин')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='noise.noisemeasurement')),
            ],
            options={
                'verbose_name': 'Точка замера',
                'verbose_name_plural': 'Точки замера',
                'ordering': ['point_number'],
            },
        ),
    ]
